In [1]:
import cv2
import numpy as np 

In [9]:
def procesar_imagen(img):
  image=cv2.imread(img,cv2.IMREAD_GRAYSCALE)
  alto,ancho=image.shape
  left_padding=(500-ancho)//2
  right_padding=500-left_padding-ancho
  new_img=cv2.copyMakeBorder(image,0,0,left_padding,right_padding,cv2.BORDER_CONSTANT,value=[255,255,255])
  return new_img

Para el procesamiento de imagenes, la idea basica es:
- Lo paso a blanco y negro
- Divido numero de casillas con negro sobre el total de casillas de la imagen

In [7]:
file = "Anuncios/test1.png"
image=cv2.imread(file,cv2.IMREAD_GRAYSCALE)
image

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 254, 254, 254],
       [255, 255, 255, ..., 253, 253, 253],
       [255, 255, 255, ..., 253, 253, 253]], dtype=uint8)

Sin embargo, hace falta aplicar otro trato a las imagenes para que el procesamiento sea el adecuado

## Estandarizado

El procesamiento de imagenes en bruto es impreciso, puesto que todas las imagenes tienen pequeñas variaciones que alteran de algun modo la proporcion de colores. En un experimento [incial](https://github.com/Lazlo420/BeaIdea/blob/main/test.ipynb), procese las imagenes de forma natural y el resultado probó ser irrelevante.

Cosas a tomar en cuenta al momento de procesar imagenes, y que pueden alterar el resultado:
- Alto
- Ancho
- Imperfecciones

El ancho se puede resolver designando un valor X a cada no de los anuncios. (Valor asignado: 500px)

El alto es un tema mas sensible, que no se si terminara de ser significativo para el ejercicio. Eso es para discutir con Beatriz



In [10]:
test=procesar_imagen(file)

En el momento de diferenciar blancos de negros, hay que escoger un threshold que cumpla con las expectativas de la profesora. Aca unos valores para que la profesora se haga una idea

#### 100

In [11]:
_,test_2=cv2.threshold(test,100,255,cv2.THRESH_BINARY)
test_2

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

#### 150

In [12]:
valor=150
_,test_2=cv2.threshold(test,valor,255,cv2.THRESH_BINARY)
test_2

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

#### 180

In [13]:
valor=180
_,test_2=cv2.threshold(test,valor,255,cv2.THRESH_BINARY)
test_2

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

#### 200

In [14]:
valor=200
_,test_2=cv2.threshold(test,valor,255,cv2.THRESH_BINARY)
test_2

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

#### 220

In [15]:
valor=220
_,test_2=cv2.threshold(test,valor,255,cv2.THRESH_BINARY)
test_2

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

#### 230

In [16]:
valor=230
_,test_2=cv2.threshold(test,valor,255,cv2.THRESH_BINARY)
test_2

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

#### 251

In [17]:
valor=251
_,test_2=cv2.threshold(test,valor,255,cv2.THRESH_BINARY)
test_2

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

#### 252

In [18]:
valor=252
_,test_2=cv2.threshold(test,valor,255,cv2.THRESH_BINARY)
test_2

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

#### 253

In [19]:
valor=253
_,test_2=cv2.threshold(test,valor,255,cv2.THRESH_BINARY)
test_2

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

#### 254

In [20]:
valor=254
_,test_2=cv2.threshold(test,valor,255,cv2.THRESH_BINARY)
test_2

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

## La funcion de negros (nombre en proceso)
Aca declaro y uso la funcion de proporciones. La matriz ahora solo es blanco y negro

In [22]:
def conteo(img):
  negros=np.sum(img==0)
  alto,ancho=img.shape
  tamanyo=alto*ancho
  return (negros/tamanyo*100)

In [24]:
# Llamar a la función para contar píxeles negros
porcentaje_negro = conteo(test_2)

# Mostrar el resultado
print("Porcentaje de píxeles negros: {:.2f}%".format(porcentaje_negro))

Porcentaje de píxeles negros: 34.31%


## Funcion de funciones

In [ ]:
def blck_prcnt(file):
    imagen=procesar_imagen(file)
    prcnt=conteo(imagen)
    print("Porcentaje de píxeles negros: {:.2f}%".format(prcnt))
    return prcnt